export const categoriesData = [
  {
    img: 'category1.png',
    title: 'zara',
    text: 'Printed satin mini dress',
    price: '£1450',
    id: 1,
  },
  {
    img: 'category2.png',
    title: 'zara',
    text: 'Printed dress with jute belt',
    price: '£65',
    id: 2,
  },
  {
    img: 'category3.png',
    title: 'zara',
    text: 'Faux suede dress ',
    price: '£69',
    id: 3,
  },
  {
    img: 'category4.png',
    title: 'zara',
    text: 'Panelled printed dress',
    price: '£50',
    id: 4,
  },
  {
    img: 'category5.png',
    title: 'zara',
    text: 'Satin dress',
    price: '£50',
    id: 5,
  },
  {
    img: 'category6.png',
    title: 'zara',
    text: 'Dress with back neckline detail',
    price: '£58',
    id: 6,
  },
  {
    img: 'category7.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 7,
  },
  {
    img: 'category8.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 8,
  },
  {
    img: 'category9.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 9,
  },
  {
    img: 'category10.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 10,
  },
  {
    img: 'category11.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 11,
  },
  {
    img: 'category12.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 12,
  },
  {
    img: 'category13.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 13,
  },
  {
    img: 'category14.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 14,
  },
  {
    img: 'category15.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 15,
  },
  {
    img: 'category16.png',
    title: 'Brand Name',
    text: 'Text Text Text',
    price: 'Price',
    id: 16,
  },
];
