name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    env:
      CI: false # Disable treating warnings as errors
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
