name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev # Trigger on push to the dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: false # Disable treating warnings as errors

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Ensure this script builds your site into the 'dist' or 'build' directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Adjust if your build output directory is different
          publish_branch: gh-pages # The branch to deploy to
